# This user will be created upon installation
initialUser:
  username: changeme
  password: changeme

landing:
  enabled: false
  image:
    repository: bamaas/fullstackfit_landing
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: gymtrack.nl

frontend:
  enabled: true
  image:
    repository: bamaas/fullstackfit_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: gymtrack.nl

backend:
  enabled: true
  image:
    repository: bamaas/fullstackfit_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: api.gymtrack.nl

database:
  enabled: true
  image:
    repository: bamaas/fullstackfit_database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistentVolume:
    enabled: false
    capacity: 512Mi
    storageClassName: longhorn
  credentials:
    username: postgres
    password: postgres

iam:
  enabled: true
  image:
    repository: bamaas/fullstackfit_iam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  # The title that will be shown on the login/register pages
  loginTitle: "GymTrack"
  ingress:
    enabled: true
    host: auth.gymtrack.nl
  # admin user to manage the iam system
  adminCredentials:
    username: iamusername
    password: iampassword
  smtpServer:
    password: "smtpServerPassword"
    replyToDisplayName: "No-reply | FitTrack"
    starttls: "true"
    auth: "true"
    port: "465"
    host: "smtpServerHost"
    replyTo: "no-reply@basmaas.nl"
    from: "no-reply@basmaas.nl"
    fromDisplayName: "FitTrack"
    ssl: "true"
    user: "smtpServerUser"