landing:
  enabled: true
  image:
    repository: bamaas/fullstackfit_landing
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: gymtrack.nl

frontend:
  image:
    repository: bamaas/fullstackfit_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: app.gymtrack.nl

backend:
  image:
    repository: bamaas/fullstackfit_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: api.gymtrack.nl

database:
  image:
    repository: bamaas/fullstackfit_database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistentVolume:
    storageClassName: longhorn
  credentials:
    username: postgres
    password: postgres

iam:
  image:
    repository: bamaas/fullstackfit_iam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: auth.gymtrack.nl
  adminCredentials:
    username: iamusername
    password: iampassword

listmonk:
  enabled: false
  image:
    repository: listmonk/listmonk
    pullPolicy: IfNotPresent
    tag: "v2.0.0"
  ingress:
    host: newsletter.gymtrack.nl