# The title that will be shown on the login/register pages
loginTitle: "GymTrack"
# This user will be created upon installation
initialUser:
  username: changeme
  password: changeme

landing:
  enabled: false
  image:
    repository: bamaas/fullstackfit_landing
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: gymtrack.nl
  resources:
    requests:
      memory: "5Mi"
      cpu: "5m"
    limits:
      memory: "50Mi"
      cpu: "10m"

frontend:
  enabled: true
  image:
    repository: bamaas/fullstackfit_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: gymtrack.nl
  resources:
    requests:
      memory: "5Mi"
      cpu: "3m"
    limits:
      memory: "50Mi"
      cpu: "10m"

backend:
  enabled: true
  image:
    repository: bamaas/fullstackfit_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: api.gymtrack.nl
  resources:
    requests:
      memory: "300Mi"
      cpu: "50m"
    limits:
      memory: "500Mi"
      cpu: "500m"

database:
  enabled: true
  image:
    repository: bamaas/fullstackfit_database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistentVolume:
    enabled: false
    capacity: 512Mi
    storageClassName: longhorn
  # Leave credentials empty to auto-generate.
  credentials:
    username: ""
    password: ""
  resources:
    requests:
      memory: "60Mi"
      cpu: "100m"
    limits:
      memory: "300Mi"
      cpu: "300m"

iam:
  enabled: true
  image:
    repository: bamaas/fullstackfit_iam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: auth.gymtrack.nl
  # Admin user to manage the iam system. Leave empty to auto-generate.
  credentials:
    username: ""
    password: ""
  smtpServer:
    password: "smtpServerPassword"
    replyToDisplayName: "No-reply | FitTrack"
    starttls: "true"
    auth: "true"
    port: "465"
    host: "smtpServerHost"
    replyTo: "no-reply@basmaas.nl"
    from: "no-reply@basmaas.nl"
    fromDisplayName: "FitTrack"
    ssl: "true"
    user: "smtpServerUser"
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "350Mi"
      cpu: "2000m"