landing:
  enabled: true
  image:
    repository: bamaas/fullstackfit_landing
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: doyoueventrack.app
    
frontend:
  image:
    repository: bamaas/fullstackfit_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: bro.doyoueventrack.app

backend:
  image:
    repository: bamaas/fullstackfit_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: api.doyoueventrack.app

database:
  image:
    repository: bamaas/fullstackfit_database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistentVolume:
    storageClassName: longhorn

iam:
  image:
    repository: bamaas/fullstackfit_iam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    host: auth.doyoueventrack.app

listmonk:
  enabled: true
  image:
    repository: listmonk/listmonk
    pullPolicy: IfNotPresent
    tag: "v2.0.0"
  ingress:
    host: newsletter.doyoueventrack.app