frontend:
  image:
    repository: bamaas/fullstackfit_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

backend:
  image:
    repository: bamaas/fullstackfit_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

database:
  image:
    repository: bamaas/fullstackfit_database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistentVolume:
    storageClassName: longhorn

iam:
  image:
    repository: bamaas/fullstackfit_iam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

landing:
  enabled: true
  image:
    repository: bamaas/fullstackfit_landing
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

listmonk:
  enabled: true
  image:
    repository: listmonk/listmonk
    pullPolicy: IfNotPresent
    tag: "v2.0.0"