landing:
  enabled: true
  image:
    repository: bamaas/fullstackfit_landing
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: gymtrack.nl

frontend:
  enabled: true
  image:
    repository: bamaas/fullstackfit_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: app.gymtrack.nl

backend:
  enabled: true
  image:
    repository: bamaas/fullstackfit_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: api.gymtrack.nl

database:
  enabled: true
  image:
    repository: bamaas/fullstackfit_database
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistentVolume:
    capacity: 512Mi
    storageClassName: longhorn
  credentials:
    username: postgres
    password: postgres

iam:
  enabled: true
  image:
    repository: bamaas/fullstackfit_iam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  ingress:
    enabled: true
    host: auth.gymtrack.nl
  # keycloak admin credentials
  adminCredentials:
    username: iamusername
    password: iampassword
  # this user will be created upon deployment and can be used to log into the Do You Even Track application.
  initialApplicationUser:
    username: changeme
    password: changeme
  smtpServer:
    password: "smtpServerPassword"
    replyToDisplayName: "No-reply | FitTrack"
    starttls: "true"
    auth: "true"
    port: "465"
    host: "smtpServerHost"
    replyTo: "no-reply@basmaas.nl"
    from: "no-reply@basmaas.nl"
    fromDisplayName: "FitTrack"
    ssl: "true"
    user: "smtpServerUser"

# listmonk is a newsletter application 
# which is used to store users e-mailadresses in as soon as they sign up.
listmonk:
  enabled: true
  image:
    repository: listmonk/listmonk
    pullPolicy: IfNotPresent
    tag: "v2.0.0"
  ingress:
    enabled: true
    host: newsletter.gymtrack.nl
  adminCredentials:
    username: admin
    password: admin
  database:
    # if create is true a new dedicated postgres container will be deployed
    create: true
    # if init is true a job will be scheduled to initialize the database 
    init: true
    image:
      repository: postgres
      pullPolicy: IfNotPresent
      tag: "12.5-alpine"
    credentials:
      username: listmonkdbusername
      password: listmonkdbpassword
    persistentVolume:
      capacity: 256Mi
      storageClass: longhorn
  settings:
    # if import is true a job will be scheduled to import smtp settings through api call on installs and upgrades
    # use with care since this will override settings that has been made through the ui.
    import: true
    image:
      repository: bamaas/listmonk_import
      pullPolicy: IfNotPresent
      tag: "v1.0.9"
    general:
      # Default `from` e-mail to show on outgoing campaign e-mails. 
      defaultFromEmail: "bas <noreply@listmonk.yoursite.com>"
      # list of e-mail addresses to which admin notifications such as import updates, campaign completion, failure etc. should be sent.
      adminNotificationEmails: 
        - admin@listmonk.yoursite.com
    smtp:
      host: "smtpServerHost"
      port: "465"
      username: "ditiseentest"
      password: "smtpServerPassword"
      authProtocol: "plain"
      tlsEnabled: "true"
      skipTlsVerification: "false"