apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - sh
        - -c
        - ./listmonk
        env:
        - name: LISTMONK_app__address
          value: 0.0.0.0:9000
        - name: LISTMONK_app__admin_password
          value: admin
        - name: LISTMONK_app__admin_username
          value: admin
        - name: LISTMONK_db__database
          value: listmonk
        - name: LISTMONK_db__db
          value: listmonk
        - name: LISTMONK_db__host
          value: database
        - name: LISTMONK_db__password
          value: postgres
        - name: LISTMONK_db__ssl_mode
          value: disable
        - name: LISTMONK_db__user
          value: postgres
        image: "{{ .Values.listmonk.image.repository }}:{{ .Values.listmonk.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.listmonk.image.pullPolicy }}
        name: listmonk
        ports:
        - containerPort: 9000
          name: 9000tcp01
          protocol: TCP
        - containerPort: 9000
          name: 80tcp01
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst