{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            IAM_URL=$(echo {{ .Values.iam.ingress.host }} | sed 's/\./\\./g')
            FRONTEND_URL=$(echo {{ .Values.frontend.ingress.host }} | sed 's/\./\\./g')
            BACKEND_URL=$(echo {{ .Values.backend.ingress.host }} | sed 's/\./\\./g')
            find /usr/share/nginx/html/*.js -type f -exec sed -i "s/api\.doyoueventrack\.app/${BACKEND_URL}/g" {} \;
            find /usr/share/nginx/html/*.js -type f -exec sed -i "s/bro\.doyoueventrack\.app/${FRONTEND_URL}/g" {} \;
            find /usr/share/nginx/html/*.js -type f -exec sed -i "s/auth\.doyoueventrack\.app/${IAM_URL}/g" {} \;
            sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/nginx.conf 
            nginx -g 'daemon off;'
        env:
          - name: PORT
            value: "4200"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
            memory: "5Mi"
            cpu: "5m"
          limits:
            memory: "50Mi"
            cpu: "10m"
        ports:
        - containerPort: 4200
          name: 4200tcp327341
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
{{- end }}