{{- if .Values.iam.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  labels:
    app: iam
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - name: iam
        image: "{{ .Values.iam.image.repository }}:{{ .Values.iam.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.iam.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            IAM_URL=$(echo {{ .Values.iam.ingress.host }} | sed 's/\./\\./g')
            LOGIN_TITLE=$(echo {{ .Values.iam.loginTitle }} | sed 's/\./\\./g')
            sed -i "s/auth\.doyoueventrack\.app/${IAM_URL}/g" /opt/jboss/keycloak/themes/FitTrack/login/template.ftl
            sed -i "s/Do You Even Track/${LOGIN_TITLE}/g" /opt/jboss/keycloak/themes/FitTrack/login/template.ftl
            /opt/jboss/keycloak/bin/add-user-keycloak.sh -r FitTrack -u {{ .Values.iam.initialApplicationUser.username }} -p {{ .Values.iam.initialApplicationUser.password }}
            /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0
        env:
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: iam
              key: USERNAME
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iam
              key: PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://{{ .Values.iam.ingress.host }}/auth"
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: PASSWORD
        - name: DB_ADDR
          value: "database"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "postgres"
        - name: DB_SCHEMA
          value: "iam"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
{{- end }}