apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: bro.doyoueventrack.app
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 4200
        pathType: ImplementationSpecific