apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: api.doyoueventrack.app
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 5000
        pathType: ImplementationSpecific