apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  managedFields:
    manager: nginx-ingress-controller
    operation: Update
  - apiVersion: extensions/v1beta1
    manager: rancher
    operation: Update
  name: auth
spec:
  rules:
  - host: auth.doyoueventrack.app
    http:
      paths:
      - backend:
          serviceName: iam
          servicePort: 8080
        pathType: ImplementationSpecific