apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: auth.doyoueventrack.app
    http:
      paths:
      - backend:
          serviceName: iam
          servicePort: 8080
        pathType: ImplementationSpecific