apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iam
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: {{ .Values.iam.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: iam
          servicePort: 8080
        pathType: ImplementationSpecific