apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  managedFields:
    manager: nginx-ingress-controller
    operation: Update
  - apiVersion: extensions/v1beta1
    manager: rancher
    operation: Update
  name: app
spec:
  rules:
  - host: bro.doyoueventrack.app
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 4200
        pathType: ImplementationSpecific