{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doyoueventrack-backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.backend.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: doyoueventrack-backend
          servicePort: http
        pathType: ImplementationSpecific
{{- end }}