apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  managedFields:
    manager: nginx-ingress-controller
    operation: Update
  - apiVersion: extensions/v1beta1
    manager: rancher
    operation: Update
  name: api
spec:
  rules:
  - host: api.doyoueventrack.app
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 5000
        pathType: ImplementationSpecific