{{- if and .Values.iam.enabled .Values.iam.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iam
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    revision: {{ Release.Revision }}
spec:
  rules:
  - host: {{ .Values.iam.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: iam
          servicePort: 8080
        pathType: ImplementationSpecific
{{- end }}