{{- if .Values.landing.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: {{ .Values.landing.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: landing
          servicePort: 80
        pathType: ImplementationSpecific
{{- end }}