{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    revision: {{ Release.Revision }}
spec:
  rules:
  - host: {{ .Values.backend.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 5000
        pathType: ImplementationSpecific
{{- end }}