apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 4200
        pathType: ImplementationSpecific