{{- if .Values.listmonk.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: listmonk
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.listmonk.persistentVolume.capacity }}
  storageClassName: {{ .Values.listmonk.persistentVolume.storageClassName }}
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.listmonk.persistentVolume.capacity }}
{{- end }}