{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: doyoueventrack-database
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistentVolume.capacity }}
  storageClassName: {{ .Values.database.persistentVolume.storageClassName }}
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.database.persistentVolume.capacity }}
{{- end }}