{{- if .Values.iam.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: doyoueventrack-iam-smtp-settings
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-4"
type: Opaque
stringData:
  smtp.json: |-
            {
              "smtpServer" : {
                "password" : "{{ .Values.iam.smtpServer.password }}",
                "replyToDisplayName" : ""{{ .Values.iam.smtpServer.replyToDisplayName }}",
                "starttls" : ""{{ .Values.iam.smtpServer.starttls }}",
                "auth" : ""{{ .Values.iam.smtpServer.auth }}",
                "port" : ""{{ .Values.iam.smtpServer.port }}",
                "host" : ""{{ .Values.iam.smtpServer.host }}",
                "replyTo" : ""{{ .Values.iam.smtpServer.replyTo }}",
                "from" : ""{{ .Values.iam.smtpServer.from }}",
                "fromDisplayName" : ""{{ .Values.iam.smtpServer.fromDisplayName }}",
                "ssl" : ""{{ .Values.iam.smtpServer.ssl }}",
                "user" : ""{{ .Values.iam.smtpServer.user }}"
              }
            }
{{- end }}