apiVersion: v1
kind: Secret
metadata:
  name: iam
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
stringData:
    USERNAME: "{{ .Values.iam.adminCredentials.username }}"
    PASSWORD: "{{ .Values.iam.adminCredentials.password }}"