{{- if .Values.iam.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: iam
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision }}
type: Opaque
stringData:
    USERNAME: "{{ .Values.iam.adminCredentials.username }}"
    PASSWORD: "{{ .Values.iam.adminCredentials.password }}"
{{- end }}