{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: doyoueventrack-database
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  POSTGRES_DB: "{{ "postgres" | b64enc}}"
  POSTGRES_USER: "{{ .Values.database.credentials.username | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.database.credentials.password | b64enc }}"
{{- end }}