apiVersion: v1
kind: Secret
metadata:
  name: database
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
stringData:
    USERNAME: "{{ .Values.database.credentials.username }}"
    PASSWORD: "{{ .Values.database.credentials.password }}"