{{- if .Values.iam.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: doyoueventrack-iam-credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
type: Opaque
data:
    {{- if .Values.iam.credentials.username }}
    KEYCLOAK_USER: "{{ .Values.iam.credentials.username | b64enc }}"
    {{- else }}
    KEYCLOAK_USER: "{{ randAlphaNum 20 | b64enc }}"
    {{- end }}
    {{- if .Values.iam.credentials.password }}
    KEYCLOAK_PASSWORD: "{{ .Values.iam.credentials.password }}"
    {{- else }}
    KEYCLOAK_PASSWORD: "{{ randAlphaNum 20 | b64enc }}"
    {{- end }}
    DOYOUEVENTRACK_USERNAME: "{{ .Values.initialUser.username | b64enc }}"
    DOYOUEVENTRACK_PASSWORD: "{{ .Values.initialUser.password | b64enc }}"
{{- end }}