apiVersion: v1
kind: Secret
metadata:
  name: doyoueventrack-iam-smtp-settings
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-4"
type: Opaque
stringData:
  smtp.json: |-
            {
              "smtpServer" : {
                "password" : "iets",
                "replyToDisplayName" : "iets | FitTrack",
                "starttls" : "true",
                "auth" : "true",
                "port" : "465",
                "host" : "smtpServerHost",
                "replyTo" : "no-reply@basmaas.nl",
                "from" : "no-reply@basmaas.nl",
                "fromDisplayName" : "FitTrack",
                "ssl" : "true",
                "user" : "smtpServerUser"
              }
            }