{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision }}
spec:
  ports:
  - name: 5432tcp-database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
  sessionAffinity: None
  type: ClusterIP
{{- end }}