{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: 4200tcp-frontend
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
{{- end }}