{{- if .Values.iam.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: iam
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: iamport-iam
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: iam
  sessionAffinity: None
  type: ClusterIP
{{- end }}