{{- if .Values.listmonk.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: listmonk-app
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: listmonk-app
  sessionAffinity: None
  type: ClusterIP
{{- end }}