apiVersion: v1
kind: Service
metadata:
  name: landing
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: 80tcp-landing
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: landing
  sessionAffinity: None
  type: ClusterIP