{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: doyoueventrack-database
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  ports:
  - name: 5432tcp-database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: doyoueventrack-database
  sessionAffinity: None
  type: ClusterIP
{{- end }}