{{- if .Values.landing.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: doyoueventrack-landing
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: doyoueventrack-landing
  sessionAffinity: None
  type: ClusterIP
{{- end }}