apiVersion: v1
kind: Service
metadata:
  name: listmonk
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: listmonkport-listmonk
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: listmonk
  sessionAffinity: None
  type: ClusterIP